https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Control_flow_and_error_handling

JavaScript 支持一组紧凑的语句，特别是控制流语句，您可以使用它们在应用程序中合并大量的交互性。本章概述了这些陈述。



#### Falsy values

以下值的计算结果为 false（也称为 Falsy 值）：

* false
* undefined
* null
* `0`
* NaN
* the empty string (`""`)

所有其他值（包括所有对象）在传递给条件语句时计算结果为 true。

> 注意：不要将原始布尔值 true 和 false 与 Boolean 对象的 true 和 false 值混淆！
>
> ```js
> const b = new Boolean(false);
> if (b) {
>   // this condition evaluates to true
> }
> if (b == true) {
>   // this condition evaluates to false
> }
> ```

在以下示例中，如果 Text 对象中的字符数为 3，则函数 checkData 返回 true。否则，它会显示警报并返回 false。

```js
function checkData() {
  if (document.form1.threeChar.value.length === 3) {
    return true;
  } else {
    alert(
      `Enter exactly three characters. ${document.form1.threeChar.value} is not valid.`,
    );
    return false;
  }
}
```



#### switch statement switch语句

switch 语句允许程序计算表达式并尝试将表达式的值与 case 标签相匹配。如果找到匹配项，程序将执行关联的语句。

```js
switch (expression) {
  case label1:
    statements1;
    break;
  case label2:
    statements2;
    break;
  // …
  default:
    statementsDefault;
}
```



#### break statements 中断语句

与每个 case 子句关联的可选的break语句确保一旦执行匹配的语句，程序就跳出switch，然后在switch后面的语句处继续执行。如果省略break，程序将继续在switch 语句内执行（并将评估下一个情况，依此类推）。



#### Exception types异常类型

几乎任何对象都可以在 JavaScript 中抛出。然而，并非所有抛出的对象都是一样的。虽然将数字或字符串作为错误抛出是很常见的，但使用专门为此目的创建的异常类型之一通常更有效：

* ECMAScript exceptions
* DOMException

```js
throw expression;
```

您可以抛出任何表达式，而不仅仅是特定类型的表达式。以下代码抛出多个不同类型的异常：

```js
throw "Error2"; // String type
throw 42; // Number type
throw true; // Boolean type
throw {
  toString() {
    return "I'm an object!";
  },
};
```



#### try...catch statement

try...catch 语句标记要尝试的语句块，并指定抛出异常时的一个或多个响应。如果抛出异常，try...catch 语句将捕获它。

try...catch 语句由一个 try 块和一个 catch 块组成，try 块包含一个或多个语句，catch 块包含指定在 try 块中引发异常时要执行的操作的语句。

换句话说，您希望 try 块成功，但如果没有成功，您希望将控制权传递给 catch 块。如果 try 块内（或在 try 块内调用的函数中）的任何语句抛出异常，则控制立即转移到 catch 块。如果 try 块中没有抛出异常，则跳过 catch 块。 finally 块在 try 和 catch 块执行之后、try...catch 语句后面的语句之前执行。

以下示例使用 try...catch 语句。该示例调用一个函数，该函数根据传递给该函数的值从数组中检索月份名称。如果该值与月份编号 (1 – 12) 不对应，则会引发异常，并显示值“InvalidMonthNo”，并且 catch 块中的语句将 MonthName 变量设置为“未知”。

```js
function getMonthName(mo) {
  mo--; // Adjust month number for array index (so that 0 = Jan, 11 = Dec)
  const months = [
    "Jan", "Feb", "Mar", "Apr", "May", "Jun",
    "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
  ];
  if (months[mo]) {
    return months[mo];
  } else {
    throw new Error("InvalidMonthNo"); // throw keyword is used here
  }
}

try {
  // statements to try
  monthName = getMonthName(myMonth); // function could throw exception
} catch (e) {
  monthName = "unknown";
  logMyErrors(e); // pass exception object to error handler (i.e. your own function)
}
```

**您可以使用 catch 块来处理 try 块中可能生成的所有异常。**

finally 块包含在 try 和 catch 块执行后要执行的语句。此外，finally 块在 try...catch...finally 语句后面的代码之前执行。

您可以嵌套一个或多个 try...catch 语句。



#### Utilizing Error objects 使用错误对象

根据错误的类型，您也许可以使用名称和消息属性来获取更精确的消息。

name 属性提供一般的 Error 类（例如 DOMException 或 Error），而 message 通常提供比将错误对象转换为字符串所获得的消息更简洁的消息。

如果您抛出自己的异常，为了利用这些属性（例如，如果您的 catch 块不区分您自己的异常和系统异常），您可以使用 Error 构造函数。

```js
function doSomethingErrorProne() {
  if (ourCodeMakesAMistake()) {
    throw new Error("The message");
  } else {
    doSomethingToGetAJavaScriptError();
  }
}

try {
  doSomethingErrorProne();
} catch (e) {
  // Now, we actually use `console.error()`
  console.error(e.name); // 'Error'
  console.error(e.message); // 'The message', or a JavaScript error message
}
```

